/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;
import java.awt.Color;
import java.awt.event.*;
        
/**
 *
 * @author Sandra
 */
public class ManejoKeyListener extends javax.swing.JFrame {

    /**
     * Creates new form ManejoKeyListener
     */
    public ManejoKeyListener() {
        initComponents();
        GestionTeclado gt = new GestionTeclado();
        caja.addKeyListener(gt);
        GestionMouse gm = new GestionMouse();
        btn.addMouseListener(gm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        caja = new javax.swing.JTextField();
        btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ManejoKeyListener");

        jLabel1.setText("jLabel1");

        caja.setText("jTextField1");

        btn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        btn.setText("Clic aqui");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caja, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(caja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      ManejoKeyListener m = new ManejoKeyListener();
      m.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JTextField caja;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

// CLASE INTERNA PARA GESTION DE EVENTOS DE TECLADO
    private class GestionTeclado implements KeyListener{
        public void keyPressed(KeyEvent e){
           
        }
        public void keyReleased(KeyEvent e){
             jLabel1.setText(caja.getText().toUpperCase());
        }
        public void keyTyped(KeyEvent e){
             
        }
    }
    
    private class GestionMouse implements MouseListener{

        @Override
        public void mouseClicked(MouseEvent e) {
        }

        @Override
        public void mousePressed(MouseEvent e) {
        }

        @Override
        public void mouseReleased(MouseEvent e) {
        }

        @Override
        public void mouseEntered(MouseEvent e) {
            btn.setBackground(Color.BLUE);
        }

        @Override
        public void mouseExited(MouseEvent e) {
            btn.setBackground(Color.WHITE);
        }
        
    }

}// CIERRA LA CLASE MANEJOKEYLISTENER
